paths:
  /api/products/:
    get:
      summary: Obtiene todos los productos
      tags:
        - Products
      responses:
        "200":
          description: Los productos fueron obtenidos satisfactoriamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Product"
        "500":
          description: Error interno del servidor, usualmente generado por una query defectuosa

  /api/products/{pid}:
    get:
      summary: Obtiene un producto a partir de su ID
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: ID del producto a solicitar
          schema:
            type: String
      responses:
        "200":
          description: El producto fue obtenido satisfactoriamente
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        "500":
          description: Error interno del servidor, usualmente generado por una query defectuosa

    put:
      summary: Actualiza un producto a partir de su ID
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: Se pasa por el path el ID del producto a modificar
          schema:
            type: String
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateProductRequest"

components:
  schemas:
    Product:
      type: object
      properties:
        name:
          type: String
          description: Nombre del producto
        description:
          type: String
          description: Descripción del producto
        price:
          type: Number
          description: Precio del producto
        category:
          type: String
          description: Categoría del producto
        availability:
          type: Number
          description: Disponibilidad del producto
        owner:
          type: String
          description: Propietario del producto (por defecto, 'admin')
      example:
        name: "Producto Ejemplo"
        description: "Descripción del producto de ejemplo"
        price: 19.99
        category: "Electrónicos"
        availability: 10
        owner: "admin"

    UpdateProductRequest:
      type: object
      properties:
        name:
          type: String
          description: Nombre del producto
        description:
          type: String
          description: Descripción del producto
        price:
          type: Number
          description: Precio del producto
        category:
          type: String
          description: Categoría del producto
        availability:
          type: Number
          description: Disponibilidad del producto
      example:
        name: "Nuevo Nombre"
        description: "Nueva descripción del producto"
        price: 24.99
        category: "Nueva Categoría"
        availability: 5